### ISSUE TITLE
Installation ckfinder 

### ISSUE THREAD

**Issue by adamostrogorski** [ckfinder/ckfinder-symfony2-bundle#10]
I want install ckfinder. In this step:
`php app/console ckfinder:download`
where should I paste the zip file? 
Because I receive errror:
[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'ZipArchive' not found

**Comment by zaak** [comment]
Hi @adamostrogorski. This error means that you do not have the [Zip extension](http://www.php.net/manual/en/book.zip.php) installed. Installing it should resolve your issue.
