### ISSUE TITLE
Installation ckfinder 

### ISSUE THREAD

**Issue by adamostrogorski** [ckfinder/ckfinder-symfony2-bundle#11]
I try install ckfinder as like in this documentation https://github.com/ckfinder/ckfinder-symfony2-bundle
but at the end I have this error:
`Attempted to load class "CustomCKFinderAuth" from namespace "AppBundle\CustomCKFinderAuth".
Did you forget a "use" statement for another namespace?`

I dont't understand why. 

In my AppKernel.php:
`		new CKSource\Bundle\CKFinderBundle\CKSourceCKFinderBundle(),`

In vendor I have:
vendor/ckfinder/ckfinder-symfony2-bundle

and namespace in files just like here: https://github.com/ckfinder/ckfinder-symfony2-bundle

I didn't change anything manually except basic configuration like here: https://github.com/ckfinder/ckfinder-symfony2-bundle

Why this happens?

Thanks for support.

**Comment by zaak** [comment]
Hi @adamostrogorski. Do you have the authentication class defined as described [here](https://github.com/ckfinder/ckfinder-symfony2-bundle#configuring-authentication) in readme?

**Comment by adamostrogorski** [comment]
Yes, I clear the cache. In  vendor/ckfinder/ckfinder-symfony2-bundle/Authentication/Authentication.php  I have:
`namespace CKSource\Bundle\CKFinderBundle\Authentication;

use CKSource\Bundle\CKFinderBundle\Authentication\AuthenticationInterface;
use Symfony\Component\DependencyInjection\ContainerAware;

/**
 * CKFinder authentication service.
 */
class Authentication extends ContainerAware implements AuthenticationInterface
{
    /**
     * {@inheritdoc}
     */
    public function authenticate()
    {
        return true;
    }
}`

Is that correct?

Thanks for help.

**Comment by zaak** [comment]
The file you pasted is a part of the bundle (it's a default authentication class which simply disables the CKFinder connector) and it's a bad idea to modify it, as it may get overwritten by `composer`. I'm going to point you to readme once again :) Please have a look: https://github.com/ckfinder/ckfinder-symfony2-bundle#configuring-authentication
You have to define a custom authentication service for CKFinder and provide its class in the configuration.

If you really want to keep you authentication logic in `vendor/ckfinder/ckfinder-symfony2-bundle/Authentication/Authentication.php` (as I said, it's a bad idea), then you have to configure connector to use that class for authentication:

```yaml
# app/config/config.yml

ckfinder:
    connector:
        authenticationClass: CKSource\Bundle\CKFinderBundle\Authentication\Authentication
```

**Comment by adamostrogorski** [comment]
Thanks, now I understand. Now this works properly. 

But I still have problem with fileloader.

How I should configure rout for fileloader?  Because I have error:

No route found for "GET /public/kcfinder/browse.php"
