### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by BoShurik** [ckfinder/ckfinder-symfony2-bundle#2]
Hello!

Do you have plans to add Symfony 3 support?

**Comment by zaak** [comment]
Hi @BoShurik! We considered this, but for now we decided to focus only on Symfony 2.8, as it's long-term support version, and there was not much interest in supporting Symfony 3 - you are the first person asking for this. Let's keep this issue open for a while and see if there's a need for this.

**Comment by abdallahmaali** [comment]
Hello 
any news about symfony 3   support

**Comment by zaak** [comment]
Hi @abdallahmaali. As stated above, we don't plan adding Symfony 3 support anytime soon.

**Comment by abdallahmaali** [comment]
Thank you @zaak   do you know any alternative    , i'm working on  a big project and we used symfony 3 
and  i am looking  for a way to mange images and files ,ckfinder the best solution for my project

**Comment by zaak** [comment]
@abdallahmaali I believe you can still use CKFinder. The manual integration would be less clean than in case of bundle, but it's still possible.

**Comment by denya-vs** [comment]
+1 for support symfony3

**Comment by robertosanval** [comment]
+1 for support symfony3

**Comment by Chokapix** [comment]
+1 for support symfony3 :+1:

**Comment by denya-vs** [comment]
For Symfony 3 I use this [bundle](https://github.com/helios-ag/FMElfinderBundle)

**Comment by mwey** [comment]
+1 for support symfony3

**Comment by Efiartes** [comment]
+1 for support symfony3

**Comment by michalmrzyk** [comment]
+1 for support Symfony3

**Comment by winds1983** [comment]
+1 for support Symfony3

**Comment by vub** [comment]
+1 for support symfony3 :+1:

**Comment by zaak** [comment]
Bundle for Symfony 3 is [here](https://github.com/ckfinder/ckfinder-symfony3-bundle) :tada: 
Closing.
