### ISSUE TITLE
CKEditor and CKfinder integration

### ISSUE THREAD

**Issue by robertosanval** [ckfinder/ckfinder-symfony2-bundle#3]
I've read the doc several times but I can't get those working together.

The samples works great and my CKEditor works great too as is but I can't get the Browse button when I click on Image button.

Any help would be appreciated.

**Comment by zaak** [comment]
Hey @robertosanval. Does this problem occur in _CKEditor Integration_ example? [Here](https://github.com/ckfinder/ckfinder-symfony2-bundle#usage) you can find a short instruction describing how to enable usage examples. _CKEditor Integration_ sample code can be found [here](https://github.com/ckfinder/ckfinder-symfony2-bundle/blob/master/Resources/views/examples/ckeditor.html.twig).

Please let me know if it was helpful.

**Comment by robertosanval** [comment]
Sorry, it was my fault, I've done it. Thanks
