### ISSUE TITLE
Support for new version of aws/aws-sdk-php

### ISSUE THREAD

**Issue by mkesicki** [ckfinder/ckfinder-symfony2-bundle#4]
Is it possible to add support for newer version of aws/aws-sdk-php ? 
https://packagist.org/packages/aws/aws-sdk-php this bundle is a little bit behind.

**Comment by zaak** [comment]
Hi @mkesicki. We have addressed this update in our internal issue tracker, but for now the connector doesn't work stable with version 3 of the SDK.

**Comment by afoeder** [comment]
any way to work around this? We somehow desperately need the Paginator feature of the v3 SDK...

**Comment by zaak** [comment]
@afoeder: There's an existing Flysystem adapter for v3 SDK: https://github.com/thephpleague/flysystem-aws-s3-v3.
It should be pretty straightforward to use it. Please have a look at http://docs.cksource.com/ckfinder3-php/howto.html#howto_custom_storage_plugin.

**Comment by afoeder** [comment]
oh yes I already saw it, but 
```
$ composer.phar why aws/aws-sdk-php
ckfinder/ckfinder-symfony2-bundle  3.3.0  requires  aws/aws-sdk-php (~2.7.17)
league/flysystem-aws-s3-v2         1.0.3  requires  aws/aws-sdk-php (~2.7)
```
so it is not only implicitly required by leage/flysystem (which we could rewrite to `flysystem-aws-s3-v3`), but also explicitly required by `ckfinder/ckfinder-symfony2-bundle`.
I thought that's what you refer to by saying "the connector doesn't work stable with v3"..

We're having a Pro license BTW if that helps :-]

**Comment by wwalc** [comment]
@afoeder please note that implementing features on demand is only available as an Assistance Package, the license itself does not cover it. If you need it ASAP, please let me know and I'll ask sales to contact you.

**Comment by bruno-ds** [comment]
hello, 
do you plan to evolve to the V3 of the SDK?
no one use the V2 on a new project (and no one should!)

IMHO, this is a no go for your file manager, I'd rather use a less rich elfinder wich provide S3 support through an up to date flysystem implementation, thant a more rich feature-full ckfinder who lock me in the past.

**Comment by zaak** [comment]
Support for AWS v3 SDK was added in newest version 3.4.2.
