### ISSUE TITLE
Suport symfony 3 ?

### ISSUE THREAD

**Issue by jankod** [ckfinder/ckfinder-symfony2-bundle#8]
I was try install on symfony 3.2 and I got error:

Problem 1
    - Installation request for ckfinder/ckfinder-symfony2-bundle ^3.3 -> satisfiable by ckfinder/ckfinder-symfony2-bundle[3.3.0].
    - Conclusion: remove symfony/symfony v3.2.2
    - Conclusion: don't install symfony/symfony v3.2.2
    - ckfinder/ckfinder-symfony2-bundle 3.3.0 requires symfony/form ~2.4 -> satisfiable by symfony/form[v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2
.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0
, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.
8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - don't install symfony/form v2.4.0|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.10|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.3|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.4|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.5|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.6|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.7|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.8|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.4.9|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.0|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.10|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.11|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.12|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.3|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.4|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.5|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.6|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.7|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.8|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.5.9|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.0|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.10|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.11|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.12|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.13|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.3|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.4|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.5|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.6|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.7|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.8|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.6.9|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.0|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.10|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.11|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.12|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.13|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.14|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.15|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.16|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.17|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.18|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.19|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.20|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.21|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.22|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.23|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.3|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.4|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.5|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.6|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.7|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.8|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.7.9|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.0|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.1|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.10|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.11|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.12|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.13|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.14|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.15|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.16|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.2|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.3|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.4|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.5|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.6|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.7|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.8|don't install symfony/symfony v3.2.2
    - don't install symfony/form v2.8.9|don't install symfony/symfony v3.2.2
    - Installation request for symfony/symfony (locked at v3.2.2, required as 3.2.*) -> satisfiable by symfony/symfony[v3.2.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by BoShurik** [comment]
Developers decide to move symfony 3 bundle to separate package
https://github.com/ckfinder/ckfinder-symfony3-bundle

**Comment by zaak** [comment]
Hi @jankod. As @BoShurik explained, bundle for Symfony 3 is in a separate package.
