### ISSUE TITLE
support for the up to date version of league/flysystem

### ISSUE THREAD

**Issue by bruno-ds** [ckfinder/ckfinder-symfony2-bundle#9]
Hello,

I'm trying to `composer require ckfinder/ckfinder-symfony2-bundle`, but it fails because you're locked to `league/flysystem 1.0.14`  while this bundle is at version 1.0.40.

Unless if you have compatibility issue, would it be possible to change your composer.json to change this ` "league/flysystem": "1.0.14",` to ` "league/flysystem": "^1.0",` ?

NB : I suppose that the same problem will occur for others dependencies locked to the revision.

complete error log : 

>   Problem 1
>     - Can only install one of: league/flysystem[1.0.14, 1.0.40].
>     - Can only install one of: league/flysystem[1.0.40, 1.0.14].
>     - Can only install one of: league/flysystem[1.0.14, 1.0.40].
>     - ckfinder/ckfinder-symfony2-bundle 3.4.1 requires league/flysystem 1.0.14 -> satisfiable by league/flysystem[1.0.14].
>     - Installation request for ckfinder/ckfinder-symfony2-bundle ^3.4 -> satisfiable by ckfinder/ckfinder-symfony2-bundle[3.4.1].
>     - Installation request for league/flysystem (locked at 1.0.40) -> satisfiable by league/flysystem[1.0.40].
>

**Comment by zaak** [comment]
Fixed in newest version 3.4.2.
